config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admins do
    root "transactions#index"
    resources :transactions
  end

  concern :api_routes do
    resources :transactions, only: [:index] do
      collection do
        post :buy
        post :withdraw
        post :sell
        post :top_up
      end
    end
    resources :balances, only: [:index]
  end

  scope module: 'api', path: 'api', defaults: { format: 'json' } do
    devise_for :users, controllers: { sessions: :sessions, registrations: :registrations }
    devise_scope :user do
      post 'register', to: 'registrations#create'
      post 'login', to: 'sessions#create'
    end
    concerns :api_routes
  end
end

app/controllers/admins/transactions_controller.rb
class Admins::TransactionsController < AdminsController
  before_action :get_transaction_id, only: [:update]

  def index
    @transactions = Transaction.where(status: 'pending')
  end

  def update
    @transaction.update_attributes(transactions_params)
    redirect_to admins_transactions_path
  end

  private

  def get_transaction_id
    @transaction = Transaction.find_or_initialize_by(id: params[:id])
  end

  def transactions_params
    params.require(:transaction).permit(:amount, :asset_id, :user_id, :status, :txnref)
  end
end

app/controllers/api/transactions_controller.rb
class Api::TransactionsController < Api::ApplicationController
  before_action :set_asset_and_user, only: [:buy, :sell, :top_up, :withdraw]

  def index
    render json: Transaction.all.map{|t| t.transaction_details_json }
  end

  def buy
    if @user.can_trade_asset('cash', params[:amount])
      buy_transaction = Buy.new(transactions_params)
      Buy.transaction do
        if buy_transaction.save
          buy_transaction.complete_transaction
          render json: {result: "OK"}
        else
          render status: 422, json: {error: 'Failed to complete transaction'}
        end
      end
    else
      render status: 422, json: {error: 'No enough cash to perform transaction'}
    end
  end

  def sell
    if @user.can_trade_asset(params[:asset], params[:amount])
      sell_transaction = Sell.new(transactions_params)
      Sell.transaction do
        if sell_transaction.save
          sell_transaction.complete_transaction
          render json: {result: "OK"}
        else
          render status: 422, json: {error: 'Failed to complete transaction'}
        end
      end
    else
      render status: 422, json: {error: 'No enough asset to perform transaction'}
    end
  end

  def top_up
    top_up_transaction = TopUp.new(transactions_params)
    TopUp.transaction do
      if top_up_transaction.save
        render json: {result: "OK"}
      else
        render status: 422, json: {error: 'Failed to complete transaction'}
      end
    end
  end

  def withdraw
    if @user.can_trade_asset('cash', params[:amount])
      withdraw_transaction = Withdraw.new(transactions_params)
      Withdraw.transaction do
        if withdraw_transaction.save!
          render json: {result: "OK"}
        else
          render status: 422, json: {error: 'Failed to complete transaction'}
        end
      end
    else
      render status: 422, json: {error: 'No enough asset to perform transaction'}
    end
  end

  private

  def set_asset_and_user
    byebug
    params[:transaction][:asset_id] = Asset.find_by_slug(params[:asset]).try(:id) if params[:asset].present?
    params[:transaction][:user_id] = @user.try(:id) if @user.present?
  end

  def transactions_params
    params.require(:transaction).permit(:amount, :asset_id, :user_id)
  end

end

app/views/admins/transactions/index.html.erb
<%= link_to destroy_admin_session_path, :method => :delete, class: 'dropdown-item' do %>
   Logout
<% end %>
<div class="card">
  <div class="card-header">
    <i class="fa fa-align-justify"></i> Pending Transactions
  </div>
  <div class="card-body">
    <table class="table table-responsive-sm roles_seperator table-striped">
      <thead>
        <tr>
          <th>Transaction ID</th>
          <th>Type</th>
          <th>Amount</th>
          <th>Asset</th>
          <th scope="col" width="40%" >Action</th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |transaction|%>
          <tr>
            <td>
              <%= transaction.txnref %><br>
            </td>
            <td>
              <%= transaction.type %>
            </td>
            <td>
              <%= transaction.amount %>
            </td>
            <td>
              <%= transaction.asset.name %>
            </td>
            <td>
              <%= link_to "Approve", admins_transaction_path(transaction, transaction: {status: 'approved'}), method: :put %>
              <%= link_to "Reject", admins_transaction_path(transaction, transaction: {status: 'rejected'}), method: :put %>
            </td>

          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>